// This file is generated by Prismic local builder. Update with care!

export { default as EmbedWithCaption } from './EmbedWithCaption'
export { default as ImageWithCaption } from './ImageWithCaption'
